## Assignment17

#### 1. Create a function that transposes a 2D matrix.

Examples

transpose_matrix([
[1, 1, 1],
[2, 2, 2],
[3, 3, 3]
]) ➞ [
[1, 2, 3],
[1, 2, 3],
[1, 2, 3]
]

transpose_matrix([
[5, 5],
[6, 7],
[9, 1]
]) ➞ [
[5, 6, 9],
[5, 7, 1]
]


In [7]:
import numpy as np
def transpose_matrix(list1):
    array1 = np.array(list1)
    return array1.transpose()
print("transpose_matrix([ [1, 1, 1], [2, 2, 2], [3, 3, 3] ]) ➞ ", transpose_matrix([ [1, 1, 1], [2, 2, 2], [3, 3, 3] ]))
print("transpose_matrix([ [5, 5], [6, 7], [9, 1] ]) ➞", transpose_matrix([ [5, 5], [6, 7], [9, 1] ]))


transpose_matrix([ [1, 1, 1], [2, 2, 2], [3, 3, 3] ]) ➞  [[1 2 3]
 [1 2 3]
 [1 2 3]]
transpose_matrix([ [5, 5], [6, 7], [9, 1] ]) ➞ [[5 6 9]
 [5 7 1]]


#### 2. Create a function that determines whether a string is a valid hex code.

A hex code must begin with a pound key # and is exactly 6 characters in length. Each character must be a digit from 0-9 or an alphabetic character from A-F. All alphabetic characters may be uppercase or lowercase.

Examples

is_valid_hex_code("#CD5C5C") ➞ True

is_valid_hex_code("#EAECEE") ➞ True

is_valid_hex_code("#eaecee") ➞ True

is_valid_hex_code("#CD5C58C") ➞ False
# Length exceeds 6

is_valid_hex_code("#CD5C5Z") ➞ False
# Not all alphabetic characters in A-F

is_valid_hex_code("#CD5C&C") ➞ False
# Contains unacceptable character

is_valid_hex_code("CD5C5C") ➞ False
# Missing #



In [141]:
def is_valid_hex_code(str1):
    if len(str1[1:])==6 and str1[0] == '#' and any(not c.isalnum() for c in str1[1:])==False:
        return True
    else:
        return False

print(is_valid_hex_code("#CD5C5C"))
print(is_valid_hex_code("#EAECEE"))
print(is_valid_hex_code("#eaecee"))
print(is_valid_hex_code("#CD5C58C"))
print(is_valid_hex_code("#CD5C5"))

True
True
True
False
False


#### 3. Given a list of math equations (given as strings), return the percentage of correct answers as a string. Round to the nearest whole number.

Examples

mark_maths(["2+2=4", "3+2=5", "10-3=3", "5+5=10"]) ➞ "75%"

mark_maths(["1-2=-2"]), "0%"

mark_maths(["2+3=5", "4+4=9", "3-1=2"]) ➞ "67%"


In [163]:
list1 = ["2+2=4", "3+2=5", "1-3=3", "5+5=10"]

In [166]:
int(list(list1[3])[0]) + int(list(list1[3])[2]) == int(list(list1[3])[4])

False

In [152]:
list(list1[0])[1]

'+'

In [154]:
int(list(list1[0])[2])

2

In [165]:
for i in range(0, len(list1)):
        if int(list(list1[i])[0]) + int(list(list1[i])[2]) == int(list(list1[i])[4]):
            print(True)
        else:
            print(False)

True
True
False
False


#### 4. There are two players, Alice and Bob, each with a 3-by-3 grid. A referee tells Alice to fill out one particular row in the grid (say the second row) by putting either a 1 or a 0 in each box, such that the sum of the numbers in that row is odd. The referee tells Bob to fill out one column in the grid (say the first column) by putting either a 1 or a 0 in each box, such that the sum of the numbers in that column is even.

Alice and Bob win the game if Alice’s numbers give an odd sum, Bob’s give an even sum, and (most important) they’ve each written down the same number in the one square where their row and column intersect.

Examples

magic_square_game([2, "100"], [1, "101"]) ➞ False

magic_square_game([2, "001"], [1, "101"]) ➞ True

magic_square_game([3, "111"], [2, "011"]) ➞ True

magic_square_game([1, "010"], [3, "101"]) ➞ False

# Two lists, Alice [row, "her choice"], Bob [column, "his choice"]



In [112]:
import numpy as np

def magic_square_game(Alice, Bob):
    # creating two arrays with zero values
    a1 = np.zeros((3,3))
    a2 = np.zeros((3,3))
    
    # deriving rownumber from alice choice
    list1 = Alice
    rownum = list1[0]-1
    
    #creating list to covert alice numbers to int format
    list11 = []
    for i in list(list1[1]):
        list11.append(int(i))
    #assigning row of zero valued matrix with alice values
    a1[rownum]=list11
        
    # deriving rownumber from bob choice
    list2 = Bob
    colnum = list2[0]-1

    #creating list to covert bob numbers to int format
    list22 = []
    for i in list(list2[1]):
        list22.append(int(i))
    #assigning column of zero valued matrix with bob values   
    a2[:,colnum]= list22
    
    return a1[rownum][colnum] == a2[rownum][colnum]
    
print(magic_square_game([2, "100"], [1, "101"]))
print(magic_square_game([2, "001"], [1, "101"]))
print(magic_square_game([3, "111"], [2, "011"]))
print(magic_square_game([1, "010"], [3, "101"]))

False
True
True
False


#### 5. From point A, an object is moving towards point B at constant velocity va (in km/hr). From point B, another object is moving towards point A at constant velocity vb (in km/hr). Knowing this and the distance between point A and B (in km), write a function that returns how much time passes until both objects meet.

Format the output like this:

"2h 23min 34s"

Examples

lets_meet(100, 10, 30) ➞ "2h 30min 0s"

lets_meet(280, 70, 80) ➞ "1h 52min 0s"

lets_meet(90, 75, 65) ➞ "0h 38min 34s


In [132]:
def convert(seconds):
    seconds = seconds % (24 * 3600)
    hour = seconds // 3600
    seconds %= 3600
    minutes = seconds // 60
    seconds %= 60
      
    return "%d:%02d:%02d" % (hour, minutes, seconds)
      

In [139]:
def lets_meet(length, speed1, speed2):
    str1 = convert(length/(speed1+speed2)*60*60)
    
    return str1.split(':')[0] + 'h '+str1.split(':')[1] + 'min '+ str1.split(':')[2] + 's '


print("lets_meet(100, 10, 30) ➞ ", lets_meet(100, 10, 30))

print("lets_meet(280, 70, 80) ➞ ", lets_meet(280, 70, 80))

print("lets_meet(90, 75, 65) ➞ ", lets_meet(90, 75, 65))


lets_meet(100, 10, 30) ➞  2h 30min 00s 
lets_meet(280, 70, 80) ➞  1h 52min 00s 
lets_meet(90, 75, 65) ➞  0h 38min 34s 
